added the gif and updated the README.md file
kaiwalyakoparkar/spell-bind pull request #61
Opened 2021-08-21 14:27 UTC by Deepa-chaurasiya01

2021-08-21 14:44 UTC, kaiwalyakoparkar commented
Could you please make them a bit slow maybe. That looks pretty flashy. No need to record entire level. Just give a preview of that level. That would work fine too.

2021-08-21 14:51 UTC, Deepa-chaurasiya01 commented
okay sir

On Sat, 21 Aug 2021 at 20:15, Kaiwalya Koparkar ***@***.***>
wrote:

> Could you please make them a bit slow maybe. That looks pretty flashy. No
> need to record entire level. Just give a preview of that level. That would
> work fine too.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/kaiwalyakoparkar/spell-bind/pull/61#issuecomment-903127170>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ASZWJ5PM5YXJY6IAYMMF5ZDT563XLANCNFSM5CR43JGA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&utm_campaign=notification-email>
> .
>

2021-08-24 04:15 UTC, kaiwalyakoparkar requested changes

2021-08-24 04:15 UTC, kaiwalyakoparkar commented on README.md
> +<img src = "assets/Screenshots/gif/Flying-w/Flying-wizard.gif
This links seems to be broken, Could you please fix it.
[Ref:]
<img src="https://i.imgur.com/GkdUfdd.png">

2021-08-24 04:15 UTC, kaiwalyakoparkar commented on README.md
> + <!-- <div class = "row">
Please remove this commented code :)

2021-08-24 04:15 UTC, kaiwalyakoparkar commented on README.md
> +  <!-- <div class = "row">
Please remove this commented code.

2021-08-24 07:03 UTC, closed without merging

2021-08-24 07:05 UTC, Deepa-chaurasiya01 commented
Sorry ! Sir, I was checking the gifs. I'm sorry!!

On Tue, 24 Aug 2021 at 09:46, Kaiwalya Koparkar ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In README.md
> <https://github.com/kaiwalyakoparkar/spell-bind/pull/61#discussion_r694477965>
> :
>
> >
>
> +<img src = "assets/Screenshots/gif/Flying-w/Flying-wizard.gif
>
>
> This links seems to be broken, Could you please fix it.
> [Ref:]
>
> <https://camo.githubusercontent.com/70252f960a9393c0d3cb7c581bfe88d48e7181618b4983b3d08c5c7e1345fa58/68747470733a2f2f692e696d6775722e636f6d2f476b64556664642e706e67>
> ------------------------------
>
> In README.md
> <https://github.com/kaiwalyakoparkar/spell-bind/pull/61#discussion_r694478093>
> :
>
> >
>
>  ## 🚩Flying Wizard:
>
>
>
> - <div class = "row">
>
> + <!-- <div class = "row">
>
>
> Please remove this commented code :)
> ------------------------------
>
> In README.md
> <https://github.com/kaiwalyakoparkar/spell-bind/pull/61#discussion_r694478211>
> :
>
> >
>
>
>
>  ## 🚩 Escape-room:
>
>
>
> -  <div class = "row">
>
> +  <!-- <div class = "row">
>
>
> Please remove this commented code.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/kaiwalyakoparkar/spell-bind/pull/61#pullrequestreview-736764557>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ASZWJ5KBCFEBGJ24RZ33X33T6MMIRANCNFSM5CR43JGA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&utm_campaign=notification-email>
> .
>